#############################################################################
#
# Tr8n Default Decoration Tokens
#
#############################################################################

strong:     "<strong>{$0}</strong>"
bold:       "<strong>{$0}</strong>"
b:          "<strong>{$0}</strong>"
em:         "<em>{$0}</em>"
italic:     "<i>{$0}</i>"
i:          "<i>{$0}</i>"
link:       "<a href='{$href}'>{$0}</a>" 
br:         "<br>{$0}"
div:        "<div id='{$id}' class='{$class}' style='{$style}'>{$0}</div>"
span:       "<span id='{$id}' class='{$class}' style='{$style}'>{$0}</span>"